// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeEvent(msg string) (Event, error) {
	message := NewMessage(msg)
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	return event, nil
}

// wire.go:

func InitializeDistinguishingTypes() DistinguishingTypes {
	return DistinguishingTypes{MyIntO: ProvideIntO(), MyIntT: ProvideIntT()}
}
